# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import lib.db.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localpart', models.CharField(help_text='\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c\u0430', max_length=64, verbose_name='Alias localpart')),
                ('recipients', models.TextField(help_text='\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u0435\u0439, \u0440\u0430\u0437\u0434\u0435\u043b\u0435\u043d\u043d\u044b\u0439 \u0437\u0430\u043f\u044f\u0442\u044b\u043c\u0438', verbose_name='\u041f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u0438')),
            ],
            options={
                'ordering': ['domain', 'localpart'],
                'verbose_name': '\u041f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c',
                'verbose_name_plural': '\u041f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c\u044b',
            },
        ),
        migrations.CreateModel(
            name='Domains',
            fields=[
                ('domain', lib.db.models.fields.FQDNField(help_text='\u041f\u043e\u043b\u043d\u043e\u0435 \u0438\u043c\u044f \u043f\u043e\u0447\u0442\u043e\u0432\u043e\u0433\u043e \u0434\u043e\u043c\u0435\u043d\u0430 (fqdn)', max_length=128, primary_key=True, serialize=False, verbose_name='\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0434\u043e\u043c\u0435\u043d')),
                ('type', models.CharField(choices=[('VIRTUAL', '\u0412\u0438\u0440\u0442\u0443\u0430\u043b\u044c\u043d\u044b\u0439 \u0434\u043e\u043c\u0435\u043d'), ('LOCAL', '\u041b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0439 \u0434\u043e\u043c\u0435\u043d'), ('RELAY', '\u0414\u043e\u043c\u0435\u043d, \u0440\u0430\u0437\u0440\u0435\u0448\u0435\u043d\u043d\u044b\u0439 \u0434\u043b\u044f \u043f\u0435\u0440\u0435\u0441\u044b\u043b\u043a\u0438 (Relay domain)')], default='VIRTUAL', max_length=10, verbose_name='\u0422\u0438\u043f \u0434\u043e\u043c\u0435\u043d\u0430')),
            ],
            options={
                'ordering': ['domain'],
                'verbose_name': '\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0439 \u0434\u043e\u043c\u0435\u043d',
                'verbose_name_plural': '\u041f\u043e\u0447\u0442\u043e\u0432\u044b\u0435 \u0434\u043e\u043c\u0435\u043d\u044b',
            },
        ),
        migrations.CreateModel(
            name='Forwards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localpart', models.CharField(blank=True, default='', help_text='\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c\u0430', max_length=64, verbose_name='Alias localpart')),
                ('domain', lib.db.models.fields.FQDNField(blank=True, default='', help_text='\u0414\u043e\u043c\u0435\u043d \u043f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c\u0430', max_length=128, verbose_name='Alias domain')),
                ('recipient_localpart', models.CharField(blank=True, default='', help_text='\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f', max_length=64, verbose_name='Recipient localpart')),
                ('recipient_domain', lib.db.models.fields.FQDNField(help_text='\u0414\u043e\u043c\u0435\u043d \u043f\u043e\u043b\u0443\u0447\u0430\u0442\u0435\u043b\u044f', max_length=128, verbose_name='Recipient domain')),
                ('priority', models.IntegerField(default=0, help_text='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442 \u043f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c\u0430, \u0434\u043b\u044f \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0438 \u043f\u043e\u0447\u0442\u044b \u0431\u0443\u0434\u0435\u0442 \u0438\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u044c\u0441\u044f \u043f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c \u0441 \u043c\u0430\u043a\u0441\u0438\u043c\u0430\u043b\u044c\u043d\u044b\u043c \u043f\u0440\u0438\u043e\u0440\u0438\u043e\u0442\u0435\u0442\u043e\u043c', verbose_name='\u041f\u0440\u0438\u043e\u0440\u0438\u0442\u0435\u0442')),
            ],
            options={
                'ordering': ['localpart', 'domain'],
                'verbose_name': '\u0423\u043b\u0443\u0447\u0448\u0435\u043d\u043d\u044b\u0439 \u043f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c',
                'verbose_name_plural': '\u0423\u043b\u0443\u0447\u0448\u0435\u043d\u043d\u044b\u0435 \u043f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c\u044b',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localpart', models.CharField(blank=True, default='', max_length=64, verbose_name='\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('passwd', models.CharField(max_length=32, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c')),
                ('quota', models.IntegerField(default=500, help_text='\u0414\u0438\u0441\u043a\u043e\u0432\u0430\u044f \u043a\u0432\u043e\u0442\u0430 \u0432 \u041c\u0411 (0 - \u0434\u043b\u044f \u043d\u0435\u043e\u0433\u0440\u0430\u043d\u0438\u0447\u0435\u043d\u043d\u043e\u0433\u043e \u044f\u0449\u0438\u043a\u0430)', verbose_name='\u041a\u0432\u043e\u0442\u0430')),
                ('enabled', models.BooleanField(default=True, help_text='\u0410\u043a\u0442\u0438\u0432\u0438\u0440\u0443\u0435\u0442 \u0434\u043e\u0441\u0442\u0430\u0432\u043a\u0443 \u043f\u043e\u0447\u0442\u044b \u0434\u043b\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f', verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d')),
                ('remote_access', models.BooleanField(default=False, help_text='\u0410\u043a\u0442\u0438\u0432\u0438\u0440\u0443\u0435\u0442 \u0440\u0430\u0431\u043e\u0442\u0443 \u0441 \u043f\u043e\u0447\u0442\u043e\u0439 \u0438\u0437 \u043d\u0435\u043b\u043e\u043a\u0430\u043b\u044c\u043d\u044b\u0445 \u0441\u0435\u0442\u0435\u0439', verbose_name='\u0423\u0434\u0430\u043b\u0435\u043d\u043d\u044b\u0439 \u0434\u043e\u0441\u0442\u0443\u043f')),
                ('domain', models.ForeignKey(default='eom.org.ua', on_delete=django.db.models.deletion.CASCADE, to='admindb.Domains', verbose_name='\u0414\u043e\u043c\u0435\u043d')),
            ],
            options={
                'ordering': ['localpart', 'domain'],
                'verbose_name': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c \u043f\u043e\u0447\u0442\u044b',
                'verbose_name_plural': '\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438 \u043f\u043e\u0447\u0442\u044b',
            },
        ),
        migrations.AlterUniqueTogether(
            name='forwards',
            unique_together=set([('localpart', 'domain', 'recipient_localpart', 'recipient_domain', 'priority')]),
        ),
        migrations.AddField(
            model_name='aliases',
            name='domain',
            field=models.ForeignKey(help_text='\u0414\u043e\u043c\u0435\u043d \u043f\u0441\u0435\u0432\u0434\u043e\u043d\u0438\u043c\u0430', on_delete=django.db.models.deletion.CASCADE, to='admindb.Domains', verbose_name='Alias domain'),
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together=set([('localpart', 'domain')]),
        ),
        migrations.AlterUniqueTogether(
            name='aliases',
            unique_together=set([('localpart', 'domain')]),
        ),
    ]
