# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='domain',
            field=models.ForeignKey(default='fakedomain.tld', on_delete=django.db.models.deletion.CASCADE, to='admindb.Domains', verbose_name='\u0414\u043e\u043c\u0435\u043d'),
        ),
    ]
