# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-06-09 09:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindb', '0002_auto_20161205_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='crypto',
            field=models.CharField(choices=[('{READY}', '{READY}'), ('{PLAIN}', '{PLAIN}'), ('{CRYPT}', '{CRYPT}')], default='{READY}', max_length=10, verbose_name='\u041a\u043e\u0434\u0438\u0440\u043e\u0432\u0430\u0442\u044c'),
        ),
        migrations.AlterField(
            model_name='users',
            name='passwd',
            field=models.CharField(default='', max_length=32, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c'),
        ),
    ]
