# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-28 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindb', '0003_auto_20170609_0931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Masters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default='', max_length=64, unique=True, verbose_name='\u0418\u043c\u044f \u0441\u0443\u043f\u0435\u0440\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f')),
                ('crypto', models.CharField(choices=[('{READY}', '{READY}'), ('{PLAIN}', '{PLAIN}'), ('{CRYPT}', '{CRYPT}')], default='{READY}', max_length=10, verbose_name='\u041a\u043e\u0434\u0438\u0440\u043e\u0432\u0430\u0442\u044c')),
                ('passwd', models.CharField(default='', max_length=32, verbose_name='\u041f\u0430\u0440\u043e\u043b\u044c')),
                ('enabled', models.BooleanField(default=True, help_text='\u0410\u043a\u0442\u0438\u0432\u0438\u0440\u0443\u0435\u0442 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f', verbose_name='\u0410\u043a\u0442\u0438\u0432\u0435\u043d')),
                ('comment', models.CharField(blank=True, help_text='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439', max_length=64, verbose_name='Comment')),
            ],
            options={
                'ordering': ['user'],
                'verbose_name': '\u0421\u0443\u043f\u0435\u0440\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044c \u043f\u043e\u0447\u0442\u044b',
                'verbose_name_plural': '\u0421\u0443\u043f\u0435\u0440\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438 \u043f\u043e\u0447\u0442\u044b',
            },
        ),
        migrations.AddField(
            model_name='aliases',
            name='comment',
            field=models.CharField(blank=True, help_text='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439', max_length=64, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='domains',
            name='comment',
            field=models.CharField(blank=True, help_text='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439', max_length=64, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='forwards',
            name='comment',
            field=models.CharField(blank=True, help_text='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439', max_length=64, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='users',
            name='comment',
            field=models.CharField(blank=True, help_text='\u041a\u043e\u043c\u043c\u0435\u043d\u0442\u0430\u0440\u0438\u0439', max_length=64, verbose_name='Comment'),
        ),
    ]
